name: CI Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - $default-branch

jobs:
  commit-validation:
    uses: observeinc/.github/.github/workflows/shared_commit-validation.yaml@main
    secrets: inherit
    with:
      skip: '{}'
