name: Release and push
on:
  workflow_dispatch:

jobs:
  bump:
    uses: observeinc/.github/.github/workflows/terraform_release.yaml@release-push
    secrets: inherit
    with:
      release-count: 1
      push: false
